# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rapousada
tagline:          'Chácara em Cavalcante'
description:      'Chácara para temporada em Cavalcante (Chapada dos Veadeiros - Goiás) com infraestrutura completa.'
url:              http://rapousada.com.br
baseurl:          /

author:
  name:           'Lenilson Alves'
  url:            http://rapousada.com.br

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rapousada/rapousada.github.io
